### PR TITLE
#106 Add delete group endpoint

### LINKED ISSUE #83: Validate Relations to Deleted Entities
If we create a Model with a relationship to a deleted entity we will not receive a foreign key violation error because the deleted entity is still in the database. If we delete a entity the deleted-at entry is set (soft-delete).

 We could create a validation to check every time if the entity is deleted
E.g: inside a BeforeCreate(tx *gorm.DB) function

OR

We could change to hard-delete. Entities will be completely removed from the database.

### LINKED ISSUE #106: Add DELETE /group/{id} endpoint
Things to consider:
- only owner should be able to remove the group
- what happens with bills? Simplest solution: delete them too

### PR DESCRIPTION
**Pull request by f-odc**
Closes #106 
Closes #83

### CODE REVIEW

**Comment by f-odc** [comment]
@GR0ZA wait with the PR please. I have to change something.

**Comment by f-odc** [comment]
> @GR0ZA wait with the PR please. I have to change something.

I added that all group associations will be deleted if a group gets deleted.

**Comment by f-odc** [comment]
The last commit changes all database models to be hard deleted in every case. I included constraints so that gorm handle the deletion of associations automatically.

This PR can be merged and will add hard deletion to PR #143.

**Comment by GR0ZA** [comment]
@f-odc 
Nice! 2 things:

1. Question:
Do we really need the "OnUpdate:CASCADE" constraint? From my experience the ON UPDATE constraint in SQL databases has just some few rare use-cases. One of them is to update the associated tables if the primary key of the 'root' changes. But it is a good practice to make the primary key not updatable, like it is in our case -> we don't want to update the ID of a group/bill/etc... Therefore - do we need this constraint? Is it something that gorm needs in order to make the deletion work properly? Or can we remove it?

2. Info:
The reason I wanted to talk with you before is that in your previous implementation you soft-deleted the entry in the "groups" table, but hard-deleted all associations of the group. That wouldn't make that much sense since the reason for using soft-delete is the possibility to restore data if it has to be. But keeping only the single entry in "groups" table without any other associated entries doesn't really fill the purpose. If we soft-delete something, we should keep all the associated entries.
This of course introduces more complexity. Let's say if for some reason we want to load all entries for some user from the group_members table, we wouldn't know which of the entries belongs to a deleted group. We would have to adjust the query making it more complex. 
Using hard delete is simpler.

**Comment by f-odc** [comment]
> @f-odc Nice! 2 things:
> 
> 1. Question:
>    Do we really need the "OnUpdate:CASCADE" constraint? From my experience the ON UPDATE constraint in SQL databases has just some few rare use-cases. One of them is to update the associated tables if the primary key of the 'root' changes. But it is a good practice to make the primary key not updatable, like it is in our case -> we don't want to update the ID of a group/bill/etc... Therefore - do we need this constraint? Is it something that gorm needs in order to make the deletion work properly? Or can we remove it?
> 2. Info:
>    The reason I wanted to talk with you before is that in your previous implementation you soft-deleted the entry in the "groups" table, but hard-deleted all associations of the group. That wouldn't make that much sense since the reason for using soft-delete is the possibility to restore data if it has to be. But keeping only the single entry in "groups" table without any other associated entries doesn't really fill the purpose. If we soft-delete something, we should keep all the associated entries.
>    This of course introduces more complexity. Let's say if for some reason we want to load all entries for some user from the group_members table, we wouldn't know which of the entries belongs to a deleted group. We would have to adjust the query making it more complex.
>    Using hard delete is simpler.

To 1. We do not need the `OnUpdate` constraint for the deletion so we could remove it. But, leave it in the code does us no harm. If the root ID somehow changes, we would be on the safe side. I would leave it in.
To 2. You are right as always. I think just using hard deletion everywhere will make live easier and our database more cleaner.

**Comment by GR0ZA** [comment]
> > @f-odc Nice! 2 things:
> > 
> > 1. Question:
> >    Do we really need the "OnUpdate:CASCADE" constraint? From my experience the ON UPDATE constraint in SQL databases has just some few rare use-cases. One of them is to update the associated tables if the primary key of the 'root' changes. But it is a good practice to make the primary key not updatable, like it is in our case -> we don't want to update the ID of a group/bill/etc... Therefore - do we need this constraint? Is it something that gorm needs in order to make the deletion work properly? Or can we remove it?
> > 2. Info:
> >    The reason I wanted to talk with you before is that in your previous implementation you soft-deleted the entry in the "groups" table, but hard-deleted all associations of the group. That wouldn't make that much sense since the reason for using soft-delete is the possibility to restore data if it has to be. But keeping only the single entry in "groups" table without any other associated entries doesn't really fill the purpose. If we soft-delete something, we should keep all the associated entries.
> >    This of course introduces more complexity. Let's say if for some reason we want to load all entries for some user from the group_members table, we wouldn't know which of the entries belongs to a deleted group. We would have to adjust the query making it more complex.
> >    Using hard delete is simpler.
> 
> To 1. We do not need the `OnUpdate` constraint for the deletion so we could remove it. But, leave it in the code does us no harm. If the root ID somehow changes, we would be on the safe side. I would leave it in. To 2. You are right as always. I think just using hard deletion everywhere will make live easier and our database more cleaner.

1. In general I would avoid using too much metatags. They add magic to the code and do some actions we can not influence (since they are controlled by gorm). To be honest if the root ID changes somehow at some point, we did something wrong :laughing: . But yeah we can keep it if you want, I wouldn't :laughing:

**Pull request merged**
