### PR TITLE
129 Clear debts

### LINKED ISSUE #129: Clear debts
Can you elaborate more on this?
Does this mean we close a group and all debts are summarized?

### PR DESCRIPTION
**Pull request by f-odc**
Closes #129 

I implemented the algorithm which creates transactions between a debtor and a creditor to clear the group balance. The implemented function should be optimal, so that the number of transactions needed to balance out the group is minimal. 
Test to check the functionality are given in transaction_test.go

### CODE REVIEW

**Comment by f-odc** [comment]
In the PR please take a closer look into the structure of the new implemented functionality. We use a class in `/util` to create transactions and these transactions will be included in a new `dto.GroupDeletionOutput`. Is this meaningful?

**Comment by f-odc** [comment]
Also how do we want to identify the debtor and creditor. Right now, only the uuid is given. Maybe it would be better to link these fields with a user model instead.

**Comment by GR0ZA** [comment]
@f-odc 
The calculations seem to return correct values. However the approach of returning open transactions on DELETE /group won't work well in the app.

Let's say user A & B are both members of group G. 

1. User A deletes group G. -> OK
2. User A gets the open transaction on deletion; the transactions can be displayed in frontend -> (OK)
3. User A opens the app 10 minutes later: there is no way to see the transactions of the group -> NOT OK
4. User B opens the app, he doesn't even get to see the open transactions (since they are returned only once, on the deletion of the group, which is gone by now) -> NOT OK

Some general input from me, we can talk about it:
- DELETE shouldn't return anything
- if we really want to delete the group completely from the DB (instead of 'resetting' it), the open transactions have to be stored somehow in the DB in order to access them later. I don't think we should delete the group though
- the easiest solution could be to add i. e. a "isClear" flag to the group entity/model and "transactions" to the group model. This flag would be set when a group is resetted. If the flag is true, we calculate the transactions and return them on every GET request. This way transactions don't have to be stored in the DB, they are calculated only when it's needed & we can easily handle this in frontend.

**Comment by f-odc** [comment]
> @f-odc The calculations seem to return correct values. However the approach of returning open transactions on DELETE /group won't work well in the app.
> 
> Let's say user A & B are both members of group G.
> 
> 1. User A deletes group G. -> OK
> 2. User A gets the open transaction on deletion; the transactions can be displayed in frontend -> (OK)
> 3. User A opens the app 10 minutes later: there is no way to see the transactions of the group -> NOT OK
> 4. User B opens the app, he doesn't even get to see the open transactions (since they are returned only once, on the deletion of the group, which is gone by now) -> NOT OK
> 
> Some general input from me, we can talk about it:
> 
> * DELETE shouldn't return anything
> * if we really want to delete the group completely from the DB (instead of 'resetting' it), the open transactions have to be stored somehow in the DB in order to access them later. I don't think we should delete the group though
> * the easiest solution could be to add i. e. a "isClear" flag to the group entity/model and "transactions" to the group model. This flag would be set when a group is resetted. If the flag is true, we calculate the transactions and return them on every GET request. This way transactions don't have to be stored in the DB, they are calculated only when it's needed & we can easily handle this in frontend.

You are right, the implemented functionality does not offer the best usability. BUT: for our MVP+ i think the current implementation is sufficient enough. Working on your requested changes would go beyond our scope. New database tables would be required and the storing of the groups would have to be adjusted. Let us leave these changes in mind for later implementation.

**Pull request merged**
