### PR TITLE
11: Restructure go backend

### PR DESCRIPTION
**Pull request by GR0ZA**

### CODE REVIEW

**Comment by f-odc** [comment]
Tests are failing:
# split-the-bill-server_test [split-the-bill-server.test]
./main_test.go:20:13: assignment mismatch: 1 variable but ephemeral.NewEphemeral returns 2 values
./main_test.go:23:15: undefined: handler.NewHandler

Change main_test.go file and run tests with: go test ./...

**Comment by f-odc** [comment]
It would be nice if the README is updated to cover the new process of changing the storage.

**Comment by f-odc** [comment]
Add a specific test folder to each folder otherwise the go tests will not find the tests:

?       split-the-bill-server/authentication    [no test files]
?       split-the-bill-server/common    [no test files]
?       split-the-bill-server/config    [no test files]
?       split-the-bill-server/dto       [no test files]
FAIL    split-the-bill-server [build failed]
?       split-the-bill-server/router    [no test files]
?       split-the-bill-server/handler   [no test files]
?       split-the-bill-server/service   [no test files]
?       split-the-bill-server/service/impl      [no test files]
?       split-the-bill-server/storage   [no test files]
?       split-the-bill-server/storage/database  [no test files]
?       split-the-bill-server/storage/database/entity   [no test files]
?       split-the-bill-server/storage/ephemeral [no test files]
?       split-the-bill-server/test/types_test   [no test files]
?       split-the-bill-server/types     [no test files]
ok      split-the-bill-server/test      (cached)

**Review by f-odc — CHANGES_REQUESTED** [review]
See PR Comments

**Comment by GR0ZA** [comment]
> Tests are failing:
> 
> # split-the-bill-server_test [split-the-bill-server.test]
> ./main_test.go:20:13: assignment mismatch: 1 variable but ephemeral.NewEphemeral returns 2 values ./main_test.go:23:15: undefined: handler.NewHandler
> 
> Change main_test.go file and run tests with: go test ./...

**Comment by GR0ZA** [comment]
As discussed: the old test structure has been restored, the tests itself fixed.

I would keep the readme.md as it is right now. I created a new task on the board to add an env variable for the used storage & to update the docs.

**Review by f-odc — APPROVED** [review]
All changes are approved. Issue for the README.md is acknowledged.

**Pull request merged**
